routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware g
roup. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.content.landing');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::get('/rekap', [App\Http\Controllers\HomeController::class, 'rekap'])->name('rekap');
Route::get('/kualitas', [App\Http\Controllers\HomeController::class, 'kualitas'])->name('kualitas');
Route::get('/peternak/{peternak_id}', [App\Http\Controllers\HomeController::class, 'peternak'])->name('peternak');
Route::get('/test', [App\Http\Controllers\HomeController::class, 'test'])->name('test');
Route::get('/peternalList', [App\Http\Controllers\PeternakController::class, 'list'])->name('peternakList');
Route::get('/inputLitter', [App\Http\Controllers\PeternakController::class, 'inputLitter'])->name('inputLitter');
Route::post('/inputLitterStore', [App\Http\Controllers\PeternakController::class, 'inputLitterStore'])->name('inputLitterStore');
Route::get('/inputLitterEdit/{id}', [App\Http\Controllers\PeternakController::class, 'inputLitterEdit'])->name('inputLitterEdit');
Route::post('/inputLitterUpdate/{id}', [App\Http\Controllers\PeternakController::class, 'inputLitterUpdate'])->name('inputLitterUpdate');
Route::get('/biodataPeternak', [App\Http\Controllers\PeternakController::class, 'biodataPeternak'])->name('biodataPeternak');
Route::get('/kmen', [App\Http\Controllers\PeternakController::class, 'kmen'])->name('kmen');
Route::get('/cek_firebase', [App\Http\Controllers\HomeController::class, 'cek_firebase'])->name('cek_firebase');

Route::prefix('peternak')->name('peternak.')->group(function() {
    Route::get('/lists', [App\Http\Controllers\PeternakController::class, 'list'])->name('list');

    Route::get('/index', [App\Http\Controllers\PeternakController::class, 'index'])->name('index');
    Route::post('/store', [App\Http\Controllers\PeternakController::class, 'store'])->name('store');
    Route::post('/update/{id}', [App\Http\Controllers\PeternakController::class, 'update'])->name('update');

});

app/Http/Controllers/PeternakController.php
<?php

namespace App\Http\Controllers;

use App\Models\inputPeternak;
use App\Models\KualitasPeternak;
use App\Models\Liter;
use App\Models\Peternakan;
use Illuminate\Http\Request;
use KMeans\Space;

class PeternakController extends Controller
{

    public function biodataPeternak(Request $request){
        $data = inputPeternak::where('peternakan_id',auth()->user()->peternakan->id)->first();
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.biodataPeternak');

    }

    public function inputLitter(){

        $item = KualitasPeternak::with(['peternakan'])->get();

        $peternak = Peternakan::all();
        $data = null;


        view()->share([
            'item' => $item,
            'data' => $data,
            'peternak' => $peternak
        ]);

        return view('admin.content.inputLitter');
    }

    public function inputLitterUpdate ($id,Request $request){
        $data = Liter::where('id',$id)->first();
        $data->peternakan_id = $request->peternak_id;
        $data->Date = $request->date;
        $data->Liter_Pagi = $request->litter_pagi;
        $data->Liter_Sore = $request->litter_sore;

        $data->save();

        return redirect()->route('inputLitter');
    }

    public function inputLitterEdit ($id){
//        dd($id);
        $item = KualitasPeternak::with(['peternakan'])->get();

        $peternak = Peternakan::all();
        $data = KualitasPeternak::with(['peternakan'])->where('id',$id)->first();


        view()->share([
            'item' => $item,
            'data' => $data,
            'peternak' => $peternak
        ]);

        return view('admin.content.inputLitter');
    }

    public function inputLitterStore(Request $request){

//        dd($request->date);
        $data = new Liter();
        $data->peternakan_id = $request->peternak_id;
        $data->Date = $request->date;
        $data->Liter_Pagi = $request->litter_pagi;
        $data->Liter_Sore = $request->litter_sore;

        $data->save();

        return redirect()->back();

    }


    public function list(){
//        dd('dqw');
        $data = Peternakan::with('inputPeternak')->get();

//        dd($data);
        view()->share([
            'data' => $data
        ]);

        return view('admin.content.listPeternak');
    }

    public function index(){
//        dd(auth()->user()->peternakan->id);
        $peternak_id = auth()->user()->peternakan->id;
        $data = inputPeternak::find($peternak_id);
//        dd($data);
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.peternak.index');
    }
    public function store(){

    }

    public function update($id,Request $request){
        $data = inputPeternak::find($id);

        $data->luas_peternakan = $request->luas_peternakan;
        $data->jumlah_sapi = $request->jumlah_sapi;
        $data->save();

        return redirect()->back();
    }

    public function kmen(){
        $points = [
            [1,1],[2,2],[3,1],[3,2],[2,3],[1,5],[1,9],[1,9]
        ];

        $space = new Space(2);

// add points to space
        foreach ($points as $i => $coordinates) {
            $space->addPoint($coordinates);
        }

//        $clusters = $space->solve(2);

//        dd($clusters);
// display the cluster centers and attached points
//        foreach ($clusters as $num => $cluster) {
//            $coordinates = $cluster->getCoordinates();
//            printf(
//                "Cluster %s [%d,%d]: %d points\n",
//                $num,
//                $coordinates[0],
//                $coordinates[1],
//                count($cluster)
//            );
//        }

        $clusters = $space->solve(2, function($space, $clusters) {
            static $iterations = 0;

            printf("Iteration: %d\n", ++$iterations);

            foreach ($clusters as $i => $cluster) {
                printf("Cluster %d [%d,%d]: %d points\n", $i, $cluster[0], $cluster[1], count($cluster));
            }
        });
    }
}

resources/views/admin/content/peternak/form.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form Carousel</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data!=null) ? route('admin.auth.carousel.update',$data->id) : route('admin.auth.carousel.store')}}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    @if($data!=null)
                                        @method('put')
                                    @endif

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{($data!=null) ? $data->name : ''}}">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="file" name="image" id="image">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Desc</label>
                                        <div class="col-sm-12 col-md-7">
                                            <textarea class="form-control @error('name') is-invalid @enderror"  name="desc" style="height: 100px">{{($data!=null) ? $data->desc : ''}}</textarea>
{{--                                            <input type="text" name="desc" id="desc" class="form-control @error('name') is-invalid @enderror" value="{{($data!=null) ? $data->name : ''}}">--}}

                                            @error('desc')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">
                                                <i class="fa fa-save"></i> Save
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection

resources/views/admin/content/peternak/index.blade.php
@extends('admin.app')

@section('content')


    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Biodata Peternak</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data==null) ? route('peternak.store') : route('peternak.update',$data->id) }}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Luas Peternak</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="luas_peternakan" id="luas_peternakan" class="form-control @error('luas_peternakan') is-invalid @enderror" value="{{($data!=null) ? $data->luas_peternakan : ''}}">
                                            @error('luas_peternakan')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jumlah Sapi </label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="jumlah_sapi" id="jumlah_sapi" class="form-control @error('jumlah_sapi') is-invalid @enderror" value="{{($data!=null) ? $data->jumlah_sapi : ''}}">

                                            @error('jumlah_sapi')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">
                                                <i class="fa fa-save"></i> Save
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection